version: '3.0'
services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    ports:
      - '${MYSQL_EXTERNAL_PORT:-2345}:3306'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_INITDB_ARGS=--encoding=UTF-8
      - TZ=Asia/Seoul
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: 'mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD'
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 10s
    volumes:
      - ./db:/var/lib/mysql
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '${API_EXTERNAL_PORT:-8888}:8888'
    environment:
      - NODE_ENV=${NODE_ENV:-alpha}
    depends_on:
      db:
        condition: 'service_healthy'
