version: '3.4'
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '${API_EXTERNAL_PORT:-8888}:8888'
    environment:
      - NODE_ENV=${NODE_ENV:-alpha}
    depends_on:
      - redis

  redis:
    image: redis:6.2.5
    command: redis-server --port 6379
    container_name: redis6379
    hostname: redis6379
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - ${REDIS_PORT:-6379}:6379

