version: '3.4'
services:
  redis:
    image: redis:6.2.5
    container_name: 42world-backend-redis
    command: redis-server --port 6379
    ports:
      - '${REDIS_PORT}:6379'

  db:
    image: mysql:8.0
    container_name: 42world-backend-db
    ports:
      - '${DB_PORT}:3306'
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER_NAME}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_INITDB_ARGS=--encoding=UTF-8
      - TZ=UTC
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: 'mysqladmin ping -h localhost -u ${DB_USER_NAME} --password=${DB_USER_PASSWORD}'
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 0s
    volumes:
      - ./db:/var/lib/mysql
