export const CONFIG_OPTIONS = 'CONFIG_OPTIONS';
export const GITHUB_CLIENT_ID = 'GITHUB_CLIENT_ID';
export const GITHUB_CLIENT_SECRET = 'GITHUB_CLIENT_SECRET';
export const JWT_SECRET = 'JWT_SECRET';
