name: deploy

on:
  push:
    branches: ['develop']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: extract version
        run: |
          VERSION=$(git rev-parse --short "$GITHUB_SHA")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images backend api
        run: |
          docker build -t 42world/backend-api:${{ env.VERSION }} -f ./infra/api.Dockerfile . --platform linux/x86_64
          docker push 42world/backend-api:${{ env.VERSION }}
          docker tag 42world/backend-api:${{ env.VERSION }} 42world/backend-api:latest
          docker push 42world/backend-api:latest

      # - name: Build and push Docker images backend admin
      #   run: |
      #     docker build -t 42world/backend-admin:latest -f ./infra/admin.Dockerfile . --platform linux/x86_64
      #     docker push 42world/backend-admin:latest
      #     docker tag 42world/backend-admin:latest 42world/backend-admin:${{ env.VERSION }}
      #     docker push 42world/backend-admin:${{ env.VERSION }}

      # - name: Build and push Docker images backend batch
      #   run: |
      #     docker build -t 42world/backend-batch:latest -f ./infra/batch.Dockerfile . --platform linux/x86_64
      #     docker push 42world/backend-batch:latest
      #     docker tag 42world/backend-batch:latest 42world/backend-batch:${{ env.VERSION }}
      #     docker push 42world/backend-batch:${{ env.VERSION }}
